name: 'Check code quality'
description: 'Checks code quality: prettier, linters, build and test'
env:
  PKM_DATA_URL: 'https://itsjavi.com/supereffective-sdk/data'
  NEXT_PUBLIC_PKM_DATA_URL: 'https://itsjavi.com/supereffective-sdk/data'
  PKM_ASSETS_URL: 'https://itsjavi.com/supereffective-assets/assets'
  NEXT_PUBLIC_PKM_ASSETS_URL: 'https://itsjavi.com/supereffective-assets/assets'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: pnpm quality-checks
