name: 'Check code quality'
description: 'Checks code quality: prettier, linters, build and test'
env:
  PKM_DATA_URL: 'https://cdn.supeffective.com/dataset'
  NEXT_PUBLIC_PKM_DATA_URL: 'https://cdn.supeffective.com/dataset'
  PKM_ASSETS_URL: 'https://cdn.supeffective.com/assets'
  NEXT_PUBLIC_PKM_ASSETS_URL: 'https://cdn.supeffective.com/assets'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: pnpm quality-checks
