import type { Metadata } from 'next'

// Default Next.js font:
// import { Inter } from 'next/font/google'

// Neobrutalism fonts:
// import { Lexend_Mega, Public_Sans, Archivo_Black, Bebas_Neue, Maven_Pro, Reem_Kufi } from 'next/font/google'

import { Reem_Kufi } from 'next/font/google'
import '../styles/globals.scss'

const baseFont = Reem_Kufi({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SuperEffective 2024',
  description: 'Generated by itsjavi.com',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode
  modal?: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={baseFont.className}>{children}{modal}</body>
    </html>
  )
}
