CREATE TABLE `gamesave` (
	`id` varchar(24) NOT NULL,
	`publicId` varchar(50),
	`game` varchar(50),
	`title` varchar(50),
	`description` varchar(500),
	`otName` varchar(15),
	`otId` varchar(15),
	`otGender` tinyint,
	`lang` varchar(10),
	`createdAt` timestamp NOT NULL,
	`updatedAt` timestamp,
	CONSTRAINT `gamesave_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pokemon` (
	`id` varchar(24) NOT NULL,
	`pokemon` varchar(50),
	`nickname` varchar(15),
	`level` varchar(15),
	`shiny` boolean,
	`createdAt` timestamp NOT NULL,
	`updatedAt` timestamp,
	`gameSaveId` varchar(50),
	`draft` boolean,
	`box` int,
	`boxSlot` int,
	`tradeBoxSlot` int,
	`tradeQuantity` int,
	`tradeBack` boolean,
	`teraType` varchar(15),
	`shadow` boolean,
	`gmax` boolean,
	`dmaxLevel` int,
	`pvpReady` boolean,
	`pvpGoTier` varchar(15),
	`pvpStyle` varchar(15),
	`originMark` varchar(15),
	`originGame` varchar(15),
	`lang` varchar(10),
	`metDate` datetime,
	`metLocation` datetime,
	`metLevel` int,
	`otName` varchar(15),
	`otId` varchar(15),
	`otGender` tinyint,
	`ball` varchar(15),
	`gender` tinyint,
	`item` varchar(15),
	`move1` varchar(15),
	`move2` varchar(15),
	`move3` varchar(15),
	`move4` varchar(15),
	`ability` varchar(15),
	`nature` varchar(15),
	`mintNature` varchar(15),
	`hpEv` int,
	`atkEv` int,
	`defEv` int,
	`spaEv` int,
	`spdEv` int,
	`speEv` int,
	`hpIv` int,
	`atkIv` int,
	`defIv` int,
	`spaIv` int,
	`spdIv` int,
	`speIv` int,
	`markings` json DEFAULT ('[0,0,0,0,0,0]'),
	`ribbons` json DEFAULT ('[]'),
	`emblems` json DEFAULT ('[]'),
	CONSTRAINT `pokemon_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `donation` (
	`id` varchar(24) NOT NULL,
	`userId` varchar(24),
	`tier` varchar(15) DEFAULT 'none',
	`totalPledged` int DEFAULT 0,
	`recurring` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL,
	`updatedAt` timestamp,
	`expiresAt` timestamp,
	`notes` varchar(500),
	`maxPokemon` int DEFAULT 4800,
	CONSTRAINT `donation_id` PRIMARY KEY(`id`)
);
