name: 'Setup project'
description: 'Sets up project and its dependencies'

env:
  NODE_VERSION: '>=20.8.0'
runs:
  using: 'composite'
  steps:
    # Setup Bun and Node
    - uses: oven-sh/setup-bun@v1

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        # registry-url: https://npm.pkg.github.com

    - uses: actions/cache@v3
      name: Setup cache for node_modules
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('bun.lockb') }}
        restore-keys: |
          node_modules-${{ hashFiles('bun.lockb') }}
          node_modules-

    - uses: actions/cache@v3
      name: Setup cache for turbo
      with:
        path: .turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - shell: bash
      run: bun install --frozen-lockfile
