name: 'Setup project'
description: 'Sets up project and its dependencies'
env:
  NODE_VERSION: '>=20.8.0'
  PNPM_VERSION: '8.9'
runs:
  using: 'composite'
  steps:
    # Setup Bun, PNPM and Node
    - uses: oven-sh/setup-bun@v1

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        # registry-url: https://npm.pkg.github.com
        cache: 'pnpm'
        cache-dependency-path: './pnpm-lock.yaml'

    - uses: actions/cache@v3
      name: Setup cache for node_modules
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          node_modules-

    - uses: actions/cache@v3
      name: Setup cache for turbo
      with:
        path: .turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - shell: bash
      run: pnpm install --frozen-lockfile
